apiVersion: v1
kind: ReplicationController
metadata:
   name: myjavaapp-rc
spec:
    replicas: 2
    selector: 
      app: myjavaapp
      
    template:
      metadata:
        labels:
          app: myjavaapp
          
      spec:
        containers:
        - name: myjavacontainer
          image: maha4iac/myjavaapp22dec24:1
          ports:
           - containerPort: 8080